config/routes.rb
Rails.application.routes.draw do
  resources :genres

  resource :session
  
  get 'signup' => 'users#new'
  
  resources :users

  # get 'movies/filter/hits' => 'movies#index', scope: "hits"
  # get 'movies/filter/flops' => 'movies#index', scope: "flops"
  get 'movies/filter/:scope' => "movies#index", as: :filtered_movies

  root "movies#index"
  resources :movies do
    resources :reviews
    resources :favorites
  end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :characterizations, dependent: :destroy
  has_many :movies, through: :characterizations
  
  validates :name, presence: true, uniqueness: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]
  
  def index
    @genres = Genre.all
  end
  
  def show
    @genre = Genre.find(params[:id])
    @movies = @genre.movies
  end
  
  def new
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to @genre, notice: "Genre successfully created!"
    else
      render :new
    end
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to @genre, notice: "Genre successfully updated!"
    else
      render :edit
    end
  end
  
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_url, alert: "Genre successfully deleted!"
  end
  
private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <%= render "shared/errors", object: @genre %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
    </ol>
    <p>
      <%= f.submit %> 
    </p
  </fieldset>
<% end %>

app/views/genres/edit.html.erb
<header id="content-header">
  <h1>Edit Genre</h1>
</header>

<%= render 'form' %>

app/views/genres/index.html.erb
<header id="content-header">
  <h1>Genres</h1>
</header>

<ul>
  <% @genres.each do |genre| %>
    <li>
      <%= link_to genre.name, genre %>
    </li>
  <% end %>
</ul>

app/views/genres/new.html.erb
<header id="content-header">
  <h1>New Genre</h1>
</header>

<%= render 'form' %>

app/views/genres/show.html.erb
<article id="user">
  <header>
    <h1><%= @genre.name %></h1>
  </header>

  <ul>
    <% @movies.each do |movie| %>
      <li>
        <%= link_to movie.title, movie %>
      </li>
    <% end %>
  </ul>
  
  <footer>
    <nav>
      <%= link_to 'Edit', edit_genre_path(@genre), class: 'button' %>
      <%= link_to 'Delete', @genre, 
                  class: 'button',
                  method: :delete, data: { confirm: 'Are you sure?' } %>
    </nav>
  </footer>
</article>